% Command Line Interface (CLI) is well-suited for automatization 
% purposes and Octave. 

% Please execute this m-file section by section to get familiar with batch
% processing for NoiseLevel on CLI.

% This m-file has been automatically generated by qMRgenBatch function.

% This script has been manually modified for MoxUnit.

% Written by: Agah Karakuzu, 2017
% =========================================================================

%% AUXILIARY SECTION - (OPTIONAL) -----------------------------------------
% -------------------------------------------------------------------------

qMRinfo('NoiseLevel'); % Display help 
[pathstr,fname,ext]=fileparts(which('NoiseLevel_batch.m'));
cd (pathstr);

%% STEP|CREATE MODEL OBJECT -----------------------------------------------
%  (1) |- This section is a one-liner.
% -------------------------------------------------------------------------

Model = NoiseLevel; % Create model object

%% STEP |CHECK DATA AND FITTING - (OPTIONAL) ------------------------------
%  (2)	|- This section will pop-up the options GUI. (MATLAB Only)
%		|- Octave is not GUI compatible. 
% -------------------------------------------------------------------------

Custom_OptionsGUI(Model);
Model = getappdata(0,'Model');


%% STEP |LOAD PROTOCOL ----------------------------------------------------
%  (3)	|- Respective command lines appear if required by NoiseLevel. 
% -------------------------------------------------------------------------

% NoiseLevel object needs 0 protocol field(s) to be assigned:
 

% --------------



%% STEP |LOAD EXPERIMENTAL DATA -------------------------------------------
%  (4)	|- Respective command lines appear if required by NoiseLevel. 
% -------------------------------------------------------------------------
% NoiseLevel object needs 2 data input(s) to be assigned:
 

% Data4D
% NoiseMask
% --------------

data = struct();
% Data4D.nii.gz contains [70   70    4  197] data.
data.Data4D=double(load_nii_data('Data4D.nii.gz'));
% NoiseMask.nii.gz contains [70  70   4] data.
data.NoiseMask=double(load_nii_data('NoiseMask.nii.gz'));
 

%% STEP |FIT DATASET ------------------------------------------------------
%  (5)  |- This section will fit data. 
% -------------------------------------------------------------------------

FitResults = FitData(data,Model,0);

FitResults.Model = Model; % qMRLab output.

%% STEP |CHECK FITTING RESULT IN A VOXEL - (OPTIONAL) ---------------------
%   (6)	|- To observe outputs, please execute the lines in this section.
% -------------------------------------------------------------------------


% outputIm = FitResults.(FitResults.fields{1});

% row = round(size(outputIm,1)/2);
% col = round(size(outputIm,2)/2);
% voxel           = [row, col, 1]; % Please adapt 3rd index if 3D. 

% Show plot.  ---> 
% figure();
% FitResultsVox   = extractvoxel(FitResults,voxel,FitResults.fields);
% dataVox         = extractvoxel(data,voxel);
% Model.plotModel(FitResultsVox,dataVox)

% Show image itself. ---> 
% figure();
% imagesc(outputIm); colorbar(); title(FitResults.fields{1});


%% STEP |SAVE -------------------------------------------------------------
%  	(7) |- Save your outputs. 
% -------------------------------------------------------------------------

if moxunit_util_platform_is_octave % ---> If Octave 

save -mat7-binary 'NoiseLevel_FitResultsOctave.mat' 'FitResults';

else % ---> If MATLAB 

qMRsaveModel(Model,'NoiseLevel.qMRLab.mat'); 

end

% You can save outputs in Nifti format using FirResultSave_nii function:
% Plase see qMRinfo('FitResultsSave_nii')




