<<<<<<< HEAD
%Place in the right folder to run
cdmfile('B1_DAM_batch.m');

warning('off','all');
%% DESCRIPTION
help B1_DAM
% Batch to generate B1map with Double-Angle Method (DAM) without qMRLab GUI (graphical user interface)
% Run this script line by line
% Written by: Ian Gagnon, 2017

%% Load dataset
% Load your parameters to create your Model
% load('MODELPamameters.mat');
load('B1_DAMParameters.mat');

%% Check data and fitting (Optional)

%**************************************************************************
% I- GENERATE FILE STRUCT
%**************************************************************************
% Create a struct "file" that contains the NAME of all data's FILES
% file.DATA = 'DATA_FILE';
file = struct;
file.SF60 = 'SF60.nii.gz';
file.SF120 = 'SF120.nii.gz';

%**************************************************************************
% II- CHECK DATA AND FITTING
%**************************************************************************
%qMRLab(Model,file);


%% Create Quantitative Maps

%**************************************************************************
% I- LOAD EXPERIMENTAL DATA
%**************************************************************************
% Create a struct "data" that contains all the data
% .MAT file : load('DATA_FILE');
%             data.DATA = double(DATA);
% .NII file : data.DATA = double(load_nii_data('DATA_FILE'));
data.SF60 = double(load_nii_data('SF60.nii.gz'));
data.SF120  = double(load_nii_data('SF120.nii.gz'));

%**************************************************************************
% II- FIT DATASET
%**************************************************************************
FitResults       = FitData(data,Model,1); % 3rd argument plots a waitbar

%**************************************************************************
% III- SAVE
%**************************************************************************
% .MAT file : FitResultsSave_mat(FitResults,folder);
% .NII file : FitResultsSave_nii(FitResults,fname_copyheader,folder);
FitResultsSave_nii(FitResults,'SF60.nii.gz');
%save('Parameters.mat','Model');

%% Check the results
% Load them in qMRLab
=======
% Command Line Interface (CLI) is well-suited for automatization 
% purposes and Octave. 

% Please execute this m-file section by section to get familiar with batch
% processing for B1_DAM on CLI.

% This m-file has been automatically generated by qMRgenBatch function. 

% This script has been manually modified for MoxUnit.

% Written by: Agah Karakuzu, 2017
% =========================================================================

%% AUXILIARY SECTION - (OPTIONAL) -----------------------------------------
% -------------------------------------------------------------------------

qMRinfo('B1_DAM'); % Display help 
[pathstr,fname,ext]=fileparts(which('B1_DAM_batch.m'));
cd (pathstr);

%% STEP|CREATE MODEL OBJECT -----------------------------------------------
%  (1) |- This section is a one-liner.
% -------------------------------------------------------------------------

Model = B1_DAM; % Create model object

%% STEP |CHECK DATA AND FITTING - (OPTIONAL) ------------------------------
%  (2)	|- This section will pop-up the options GUI. (MATLAB Only)
%		|- Octave is not GUI compatible. 
% -------------------------------------------------------------------------

if not(moxunit_util_platform_is_octave) % ---> If MATLAB
Custom_OptionsGUI(Model);
Model = getappdata(0,'Model');
end



%% STEP |LOAD PROTOCOL ----------------------------------------------------
%  (3)	|- Respective command lines appear if required by B1_DAM. 
% -------------------------------------------------------------------------

% This object does not have protocol attributes.
 



%% STEP |LOAD EXPERIMENTAL DATA -------------------------------------------
%  (4)	|- Respective command lines appear if required by B1_DAM. 
% -------------------------------------------------------------------------
% B1_DAM object needs 2 data input(s) to be assigned:
 

% SF60
% SF120
% --------------

data = struct();
% SF120.nii.gz contains [64  64] data.
data.SF60=double(load_nii_data('SF120.nii.gz'));
% SF60.nii.gz contains [64  64] data.
data.SF120=double(load_nii_data('SF60.nii.gz'));
 

%% STEP |FIT DATASET ------------------------------------------------------
%  (5)  |- This section will fit data. 
% -------------------------------------------------------------------------

FitResults = FitData(data,Model,0);

FitResults.Model = Model; % qMRLab output.

%% STEP |CHECK FITTING RESULT IN A VOXEL - (OPTIONAL) ---------------------
%   (6)	|- To observe outputs, please execute the lines in this section.
% -------------------------------------------------------------------------


% outputIm = FitResults.(FitResults.fields{1});

% row = round(size(outputIm,1)/2);
% col = round(size(outputIm,2)/2);
% voxel           = [row, col, 1]; % Please adapt 3rd index if 3D. 

% Show plot.  ---> 
% figure();
% FitResultsVox   = extractvoxel(FitResults,voxel,FitResults.fields);
% dataVox         = extractvoxel(data,voxel);
% Model.plotModel(FitResultsVox,dataVox)

% Show image itself. ---> 
% figure();
% imagesc(outputIm); colorbar(); title(FitResults.fields{1});


%% STEP |SAVE -------------------------------------------------------------
%  	(7) |- Save your outputs. 
% -------------------------------------------------------------------------

if moxunit_util_platform_is_octave % ---> If Octave 

save -mat7-binary 'B1_DAM_FitResultsOctave.mat' 'FitResults';

else % ---> If MATLAB 

qMRsaveModel(Model,'B1_DAM.qMRLab.mat'); 

end

% You can save outputs in Nifti format using FirResultSave_nii function:
% Plase see qMRinfo('FitResultsSave_nii')




>>>>>>> 2ee6d2dbaf24f87e1f346d1412f3361c6f9206e2
