function ViewPulse(Pulse, field)
%VIEWPULSE Plose an RF pulse structure.
%   ViewPulse(Pulse, field)
%
%   --args--
%   Pulse: RF Pulse structure (generated by GETPULSE).
%   field: Pulse property to be ploted. 
%
%          -values-
%          'b1'
%          'omega'
%          'omega2'
%
%   See also GETPULSE.
%

for ii = 1:length(Pulse)
    Trf = Pulse(ii).Trf;
    t = 0:Trf/1000:Trf;
    y = Pulse(ii).(field)(t);
    plot(t*1000,y, 'LineWidth', 2); hold on;
    leg{ii} = [Pulse(ii).shape];
end

ylim([min(y)*1.2 max(y)*1.2])
legend(leg);
xlabel('Time (ms)');
ylabel(field);

end
