function dM = BlochNoMT(t, M, T2f, Pulse)
%BLOCHNOMT Free pool ODEs with RF pulse excitation, without MT effect or T1 
%recovery
%   dM = BlochNoMT(t, M, T2f, Pulse)
%
%   --args--
%   t: Function handle variable, represents the time.
%   M: magnetization vector [Mxf, Myf, Mzf]
%   T2f: Transfer relaxation time of free-pool water protons (seconds). 
%   Pulse: RF Pulse structure (generated by GETPULSE).
%
%   Reference: Robert W. Brown, Yu-Chung N. Cheng, E. Mark Haacke, Michael 
%              R. Thompson, Ramesh Venkatesan. Magnetic Resonance Imaging: 
%              Physical Principles and Sequence Design, Second Edition, 
%              pp. 62-63, Eqs. 4.37-4.39
%
%   See also GETPULSE, BLOCH, BLOCHSOL.
%

dM    =  zeros(3,1);
omega =  Pulse.omega(t);
delta =  Pulse.delta;

dM(1) = - M(1)/T2f - 2*pi*delta*M(2);
dM(2) = - M(2)/T2f + 2*pi*delta*M(1) + omega*M(3);
dM(3) = - omega*M(2);

end
