name: MATLAB CI

on:
  push:
  pull_request:

env:
  MATLAB_PRODUCTS: >-
    Image_Processing_Toolbox
    Optimization_Toolbox
    Statistics_and_Machine_Learning_Toolbox

jobs:
  moxunit_tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: quickMoxTests
            tests: Test/MoxUnitCompatible/quickMoxTests
            report: Test/MoxUnitCompatible/quickMoxTests/coverage_quickMoxTests.json

          - name: MATLAB_1_quickMox_BatchExamplePart1
            tests: Test/MoxUnitCompatible/BatchExample_test.m
            report: Test/MoxUnitCompatible/coverage_BatchExample_test.json

          - name: MATLAB_2_BatchExamplePart2
            tests: Test/MoxUnitCompatible/BatchExamplePart2
            report: Test/MoxUnitCompatible/BatchExamplePart2/coverage_BatchExamplePart2.json

          - name: MATLAB_3_SimTests
            tests: Test/MoxUnitCompatible/simTests
            report: Test/MoxUnitCompatible/simTests/coverage_simTests.json

          - name: MATLAB_4_OtherTests
            tests: Test/MoxUnitCompatible/other
            report: Test/MoxUnitCompatible/other/coverage_other.json

          - name: MATLAB_5_EquationTests
            tests: Test/MoxUnitCompatible/equation_test
            report: Test/MoxUnitCompatible/equation_test/coverage_equation.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: ${{ env.MATLAB_PRODUCTS }}

      - name: Run MATLAB tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            startup;
            qMRLabVer;
            res = moxunit_runtests('${{ matrix.tests }}','-recursive','-with_coverage','-cover','src','-cover_exclude','*GUI*','-cover_json_file','${{ matrix.report}}');
            exit(~res);

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ${{ matrix.report }}
          flags: matlab
          fail_ci_if_error: false


  matlab_tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MATLAB_6_CommonTests
            tests: Test/Common
            report: Test/Common/coverage_common.xml
          - name: MATLAB_7_ModelsTests
            tests: Test/Models
            report: Test/Models/coverage_models.xml
          - name: MATLAB_8_ModelsFunctionsTests
            tests: Test/Models_Functions
            report: Test/Models_Functions/coverage_models_functions.xml

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: ${{ env.MATLAB_PRODUCTS }}

      - name: Run MATLAB tests
        uses: matlab-actions/run-command@v2
        with:
          command: |
            startup;
            qMRLabVer;
            [testResults, coverageResults] = runtests('${{ matrix.tests }}', 'ReportCoverageFor', 'src', 'IncludeSubfolders', true);
            coverageResults.generateCoberturaReport('${{ matrix.report }}');
            allPassed = all([testResults.assertSuccess().Passed]);
            exit(~allPassed);

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ${{ matrix.report }}
          flags: matlab
          fail_ci_if_error: false
